version: '3.8'


services:

  web:

    build:
      context: ..
      dockerfile: DOCKER-FILES/dockerfile

    image: farmacia-web:latest

    container_name: farmacia-web

    ports:

      - "9010:80"

    volumes:

      - ../PHP:/var/www/html
      - ../CSS:/var/www/html/css
      - ../LOG:/var/www/html/logs
      - ../images:/var/www/html/images
      - php-sessions:/var/lib/php/sessions
      - apache-logs:/var/log/apache2

    environment:

      - DB_HOST=db

      - DB_NAME=farmacia

      - DB_USER=sti

      - DB_PASSWORD=stiAlpha@2016

      - TZ=America/Sao_Paulo

      - JWT_SECRET_KEY=bb46a51fd2a57d09a415c11803f1176a6dbb362b3d59dc42985d424d5121b03ccf4c5671cb203bc81e1dd51cb2111a0a5ea80e6b660a3a1a24940c68813b13f0

    depends_on:

      db:

        condition: service_healthy

    networks:

      - farmacia-network

    restart: unless-stopped


  db:

    image: mysql:8.0

    container_name: farmacia-db

    volumes:

      - db_data:/var/lib/mysql

      - ../DOCKER-FILES/init.sql:/docker-entrypoint-initdb.d/init.sql

    environment:

      - MYSQL_ROOT_PASSWORD=stiAlpha@2016

      - MYSQL_DATABASE=farmacia

      - MYSQL_USER=sti

      - MYSQL_PASSWORD=stiAlpha@2016

      - TZ=America/Sao_Paulo

      - LANG=pt_BR.UTF-8

    healthcheck:

      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pHakETodLEfRe"]

      interval: 10s

      timeout: 20s

      retries: 10

    networks:

      - farmacia-network

    restart: unless-stopped


volumes:

  db_data:

    driver: local

  php-sessions:

  apache-logs:


networks:

  farmacia-network:

    driver: bridge

    attachable: true
